import os
import chromadb


try:
    client = chromadb.PersistentClient(path="./vanna_knowledge_base")
    collection = client.get_collection("vanna_collection")

    # Define the fully optimized schema definition for dim_pegawai with strong teacher/dosen mapping keywords
    dim_pegawai_schema = """Database Table Definition Asset:
Table: kepegawaian.dim_pegawai
Columns:
  - id_pegawai (character varying)
  - id_sdm_mihc (character varying)
  - nip (character varying)
  - id_simpeg_mihc (character varying)
  - nip_akademik_simpeg (character varying)
  - id_jenis_pegawai (integer)
  - jenis_pegawai (character varying)
  - nama (character varying)
  - nama_versi_akademik (character varying)
  - nama_versi_kepegawaian (character varying)
  - status_pegawai (character varying)
  - tanggal_masuk (timestamp without time zone)
  - tanggal_keluar (timestamp without time zone)
  - id_status_aktif (character varying)
  - nama_status_aktif (character varying)
  - status_aktif_simple (character varying)
  - id_satker (character varying)
  - unit (character varying)
  - jurusan (character varying)
  - fakultas (character varying)
  - nama_fungsional (character varying)
  - level_jfungsional (smallint)
  - nilai_jfungsional (integer)
  - tmt_jfungsional (timestamp without time zone)
  - nama_jabatan_umum (character varying)
  - level_jumum (smallint)
  - nilai_jumum (integer)
  - tmt_jabatan_umum (timestamp without time zone)
  - jenis_kelamin (character varying)
  - tempat_lahir (character varying)
  - tgl_lahir (timestamp without time zone)
  - agama (character varying)
  - nik (character varying)
  - npwp (character varying)
  - no_rekening (character varying)
  - alamat (character varying)
  - alamat_ktp (character varying)
  - telepon (character varying)
  - no_hp (character varying)
  - email (character varying)
  - email2 (character varying)
  - nidn (character varying)
  - nuptk (character varying)
  - nira_serdos (character varying)
  - nira_bkd (character varying)
  - id_satker_struktural (character varying)
  - id_struktural (integer)
  - nama_jstruktural (character varying)
  - jenis_struktural (character varying)
  - level_jstruktural (smallint)
  - nilai_jstruktural (integer)
  - tmt_struktural (timestamp without time zone)
  - tmt_akhir_struktural (timestamp without time zone)
  - tst_struktural (timestamp without time zone)
  - is_struktural_plt (smallint)
  - id_satker_struktural_2 (character varying)
  - id_struktural_2 (integer)
  - nama_jstruktural_2 (character varying)
  - jenis_struktural_2 (character varying)
  - level_jstruktural_2 (smallint)
  - nilai_jstruktural_2 (integer)
  - tmt_struktural_2 (timestamp without time zone)
  - tmt_akhir_struktural_2 (timestamp without time zone)
  - tst_struktural_2 (timestamp without time zone)
  - is_struktural_plt_2 (smallint)
  - no_sertifikasi (character varying)
  - tgl_sertifikasi (timestamp without time zone)
  - gelar_depan (character varying)
  - gelar_depan_2 (character varying)
  - gelar_belakang (character varying)
  - gelar_belakang_2 (character varying)
  - gelar_prof (character varying)
  - tgl_pensiun (timestamp without time zone)
  - tmt_cpns (timestamp without time zone)
  - tmt_non_cpns (timestamp without time zone)
  - tmt_pns (timestamp without time zone)
  - tmt_non_pns (timestamp without time zone)
  - tmt_honorer (integer)
  - golongan (character varying)
  - namapangkat (character varying)
  - tmt_pangkat (timestamp without time zone)
  - nama_jenis_pangkat (character varying)
  - pendidikan_versi_kepegawaian (character varying)
  - pendidikan_status_versi_kepegawaian (character varying)
  - pendidikan_bidang_versi_kepegawaian (character varying)
  - nama_institusi_versi_kepegawaian (character varying)
  - negara_institusi_versi_kepegawaian (character varying)
  - pendidikan_tertinggi (character varying)
  - pendidikan_status (character varying)
  - pendidikan_bidang (character varying)
  - nama_institusi (character varying)
  - negara_institusi (character varying)
  - id_scopus (character varying)
  - id_sinta (character varying)
  - id_lab (character varying)
  - sso_id (character varying)
  - finger_id (integer)
  - has_nonpns (integer)
  - id (integer)
  - version (integer)
  - start_date (timestamp without time zone)
  - expired_date (timestamp without time zone)
Semantic Keywords & Translation Encodings: dosen, pengajar, guru, lecturer, teacher, staf akademik pengajar, data dosen, NIDN, serdos, pegawai, karyawan, status dosen aktif, daftar pendidik, tenaga fungsional pengajar, civitas akademika dosen"""

    # Update/Upsert the definition directly
    collection.upsert(
        ids=["schema_kepegawaian_dim_pegawai_definition"],
        documents=[dim_pegawai_schema],
        metadatas=[{"type": "schema_ddl"}]
    )
    print("[SUCCESS] ChromaDB has been trained to map 'teachers' and 'dosen' to the kepegawaian.dim_pegawai table!")

except Exception as e:
    print(f"[ERROR] Failed to update ChromaDB weights: {e}")